// <auto-generated />
using System;
using DashStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406092100_addNewSeeding")]
    partial class addNewSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2,
                            Name = "Laptops & PCs"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3,
                            Name = "Audio & Sound"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 4,
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Forged in titanium with the revolutionary A17 Pro chip.",
                            ImageUrl = "https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=800",
                            Price = 159900.0,
                            SpecificationsJson = "{\"Color\":[\"Natural Titanium\",\"Blue Titanium\"],\"Storage\":[\"256GB\",\"1TB\"],\"RAM\":[\"8GB\"]}",
                            Title = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Galaxy AI is here. Embedded S-Pen and titanium exterior.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 129999.0,
                            SpecificationsJson = "{\"Color\":[\"Titanium Black\",\"Titanium Gray\"],\"Storage\":[\"256GB\",\"512GB\"],\"RAM\":[\"12GB\"]}",
                            Title = "Samsung Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The pro-level Pixel with advanced AI camera features.",
                            ImageUrl = "https://images.unsplash.com/photo-1697525381593-9c869094fe26?q=80&w=800",
                            Price = 106999.0,
                            SpecificationsJson = "{\"Color\":[\"Obsidian\",\"Bay Blue\"],\"Storage\":[\"128GB\",\"256GB\"],\"RAM\":[\"12GB\"]}",
                            Title = "Google Pixel 8 Pro"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Smooth beyond belief with Snapdragon 8 Gen 3.",
                            ImageUrl = "https://images.unsplash.com/photo-1715437803023-74b5c77742bc?q=80&w=800",
                            Price = 64999.0,
                            SpecificationsJson = "{\"Color\":[\"Flowy Emerald\",\"Silky Black\"],\"Storage\":[\"256GB\",\"512GB\"],\"RAM\":[\"12GB\",\"16GB\"]}",
                            Title = "OnePlus 12"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Unfold a massive screen for immersive productivity.",
                            ImageUrl = "https://images.unsplash.com/photo-1691435424756-32d8493f663f?q=80&w=800",
                            Price = 154999.0,
                            SpecificationsJson = "{\"Color\":[\"Phantom Black\",\"Icy Blue\"],\"Storage\":[\"512GB\",\"1TB\"],\"RAM\":[\"12GB\"]}",
                            Title = "Samsung Galaxy Z Fold 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Come to the bright side with the Glyph Interface.",
                            ImageUrl = "https://images.unsplash.com/photo-1689254060377-5047b36f73d1?q=80&w=800",
                            Price = 44999.0,
                            SpecificationsJson = "{\"Color\":[\"Dark Grey\",\"White\"],\"Storage\":[\"256GB\",\"512GB\"],\"RAM\":[\"12GB\"]}",
                            Title = "Nothing Phone (2)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Photography reinvented with Leica optics.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 99999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White\"],\"Storage\":[\"512GB\"],\"RAM\":[\"16GB\"]}",
                            Title = "Xiaomi 14 Ultra"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Dynamic Island, 48MP Main camera, USB-C.",
                            ImageUrl = "https://images.unsplash.com/photo-1696423602143-6c845b469493?q=80&w=800",
                            Price = 79900.0,
                            SpecificationsJson = "{\"Color\":[\"Pink\",\"Blue\",\"Black\"],\"Storage\":[\"128GB\",\"256GB\"],\"RAM\":[\"6GB\"]}",
                            Title = "iPhone 15"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Beyond gaming. Unmatched performance and cooling.",
                            ImageUrl = "https://images.unsplash.com/photo-1715437803023-74b5c77742bc?q=80&w=800",
                            Price = 94999.0,
                            SpecificationsJson = "{\"Color\":[\"Phantom Black\"],\"Storage\":[\"512GB\"],\"RAM\":[\"16GB\"]}",
                            Title = "Asus ROG Phone 8 Pro"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "AI-powered camera and ultra-fast charging.",
                            ImageUrl = "https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=800",
                            Price = 31999.0,
                            SpecificationsJson = "{\"Color\":[\"Black Beauty\",\"Luxe Lavender\"],\"Storage\":[\"256GB\"],\"RAM\":[\"8GB\",\"12GB\"]}",
                            Title = "Motorola Edge 50 Pro"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "The essential Google phone at a great price.",
                            ImageUrl = "https://images.unsplash.com/photo-1683935293214-3d964f40f2f3?q=80&w=800",
                            Price = 43999.0,
                            SpecificationsJson = "{\"Color\":[\"Sea\",\"Charcoal\",\"Snow\"],\"Storage\":[\"128GB\"],\"RAM\":[\"8GB\"]}",
                            Title = "Google Pixel 7a"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "The ultimate pocket-sized self-expression tool.",
                            ImageUrl = "https://images.unsplash.com/photo-1691435424756-32d8493f663f?q=80&w=800",
                            Price = 99999.0,
                            SpecificationsJson = "{\"Color\":[\"Mint\",\"Graphite\"],\"Storage\":[\"256GB\"],\"RAM\":[\"8GB\"]}",
                            Title = "Samsung Galaxy Z Flip 5"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Mind-blowing performance for the heaviest workflows.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800",
                            Price = 349900.0,
                            SpecificationsJson = "{\"Processor\":[\"Apple M3 Max\"],\"RAM\":[\"36GB\",\"64GB\"],\"Storage\":[\"1TB SSD\"]}",
                            Title = "MacBook Pro 16\" M3 Max"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "A perfect balance of power and portability for creators.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632559-0c6d3fc72635?q=80&w=800",
                            Price = 185000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core i7\",\"Intel Core i9\"],\"RAM\":[\"16GB\",\"32GB\"],\"GPU\":[\"RTX 4060\"]}",
                            Title = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "The gold standard for premium business laptops.",
                            ImageUrl = "https://images.unsplash.com/photo-1632733711679-5292d7763695?q=80&w=800",
                            Price = 165000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core i7-1355U\"],\"RAM\":[\"16GB\",\"32GB\"],\"Storage\":[\"512GB SSD\"]}",
                            Title = "Lenovo ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Ultra-portable 14-inch gaming laptop with OLED display.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 145000.0,
                            SpecificationsJson = "{\"Processor\":[\"AMD Ryzen 9\"],\"RAM\":[\"16GB\",\"32GB\"],\"GPU\":[\"RTX 4070\"]}",
                            Title = "ASUS ROG Zephyrus G14"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Lean. Mean. M3 machine.",
                            ImageUrl = "https://images.unsplash.com/photo-1611186871348-b1ec696e5237?q=80&w=800",
                            Price = 134900.0,
                            SpecificationsJson = "{\"Processor\":[\"Apple M3\"],\"RAM\":[\"8GB\",\"16GB\"],\"Storage\":[\"256GB SSD\",\"512GB SSD\"]}",
                            Title = "MacBook Air 15\" M3"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Stunning 2-in-1 design with an OLED touch display.",
                            ImageUrl = "https://images.unsplash.com/photo-1544731612-de7f96afe55f?q=80&w=800",
                            Price = 139999.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core Ultra 7\"],\"RAM\":[\"16GB\"],\"Storage\":[\"1TB SSD\"]}",
                            Title = "HP Spectre x360 14"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Empower your studio with the M2 Ultra chip.",
                            ImageUrl = "https://images.unsplash.com/photo-1629131726692-1accd0c93ce0?q=80&w=800",
                            Price = 419900.0,
                            SpecificationsJson = "{\"Processor\":[\"Apple M2 Ultra\"],\"RAM\":[\"64GB\",\"128GB\"],\"Storage\":[\"1TB SSD\"]}",
                            Title = "Apple Mac Studio"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Redesigned high-performance liquid-cooled gaming desktop.",
                            ImageUrl = "https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=800",
                            Price = 245000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core i9-14900KF\"],\"GPU\":[\"RTX 4080\",\"RTX 4090\"],\"RAM\":[\"32GB\"]}",
                            Title = "Alienware Aurora R16"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "A massive 17-inch screen in an impossibly light chassis.",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800",
                            Price = 125000.0,
                            SpecificationsJson = "{\"Weight\":[\"1.35 kg\"],\"Processor\":[\"Intel Core i7\"],\"RAM\":[\"16GB\"]}",
                            Title = "LG Gram 17"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "The world's first dual-mode mini-LED gaming display.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 320000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core i9-14900HX\"],\"GPU\":[\"RTX 4090\"],\"RAM\":[\"32GB\"]}",
                            Title = "Razer Blade 16"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Built for business, with AI-powered features.",
                            ImageUrl = "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800",
                            Price = 145000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core Ultra 5\",\"Intel Core Ultra 7\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB SSD\"]}",
                            Title = "Microsoft Surface Laptop 6"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Compact, quiet, and exceptionally powerful PC.",
                            ImageUrl = "https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=800",
                            Price = 350000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel Core i9\"],\"GPU\":[\"RTX 4090\"],\"RAM\":[\"64GB DDR5\"]}",
                            Title = "Corsair One i500"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Industry-leading noise cancellation headphones.",
                            ImageUrl = "https://images.unsplash.com/photo-1644794106430-22d74189d704?q=80&w=800",
                            Price = 29990.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"Silver\",\"Midnight Blue\"],\"Battery Life\":[\"30 Hours\"],\"Features\":[\"ANC\"]}",
                            Title = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Magical audio experience with adaptive transparency.",
                            ImageUrl = "https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?q=80&w=800",
                            Price = 24900.0,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Charging\":[\"USB-C\"],\"Features\":[\"ANC\",\"Spatial Audio\"]}",
                            Title = "Apple AirPods Pro 2"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "World-class noise cancellation with spatial audio.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800",
                            Price = 35900.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White Smoke\"],\"Battery Life\":[\"24 Hours\"],\"Features\":[\"Immersive Audio\"]}",
                            Title = "Bose QuietComfort Ultra"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Audiophile-inspired sound and 60-hour battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1524670497267-35d7a81c17e2?q=80&w=800",
                            Price = 34990.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White\"],\"Battery Life\":[\"60 Hours\"],\"Driver\":[\"42mm Transducer\"]}",
                            Title = "Sennheiser Momentum 4"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Bold sound for every adventure. Waterproof and dustproof.",
                            ImageUrl = "https://images.unsplash.com/photo-1589003077984-894e133dabab?q=80&w=800",
                            Price = 11999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"Blue\",\"Red\"],\"Battery Life\":[\"12 Hours\"],\"Durability\":[\"IP67\"]}",
                            Title = "JBL Flip 6"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Next-level spatial audio that fills the room.",
                            ImageUrl = "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800",
                            Price = 44999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White\"],\"Connectivity\":[\"Wi-Fi\",\"Bluetooth\",\"Line-in\"]}",
                            Title = "Sonos Era 300"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "Heavyweight sound in a compact, iconic frame.",
                            ImageUrl = "https://images.unsplash.com/photo-1524289286702-f07229da36f5?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Color\":[\"Black and Brass\",\"Cream\"],\"Battery Life\":[\"30\\u002B Hours\"],\"Durability\":[\"IP67\"]}",
                            Title = "Marshall Emberton II"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "24-bit Hi-Fi audio for the ultimate listening experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800",
                            Price = 16999.0,
                            SpecificationsJson = "{\"Color\":[\"Graphite\",\"White\",\"Bora Purple\"],\"Features\":[\"Active Noise Canceling\"]}",
                            Title = "Samsung Galaxy Buds 2 Pro"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Description = "The ultimate wireless HiFi speakers.",
                            ImageUrl = "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800",
                            Price = 249000.0,
                            SpecificationsJson = "{\"Type\":[\"Active Bookshelf\"],\"Streaming\":[\"AirPlay 2\",\"Chromecast\",\"Roon\"]}",
                            Title = "KEF LS50 Wireless II"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "The legendary vocal microphone for broadcasting and podcasting.",
                            ImageUrl = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800",
                            Price = 38999.0,
                            SpecificationsJson = "{\"Type\":[\"Dynamic\"],\"Polar Pattern\":[\"Cardioid\"],\"Connection\":[\"XLR\"]}",
                            Title = "Shure SM7B"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Description = "Professional studio monitor headphones.",
                            ImageUrl = "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=800",
                            Price = 14500.0,
                            SpecificationsJson = "{\"Type\":[\"Closed-Back\"],\"Connection\":[\"Wired\"],\"Driver\":[\"45mm\"]}",
                            Title = "Audio-Technica ATH-M50x"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "Super-portable wireless Bluetooth speaker.",
                            ImageUrl = "https://images.unsplash.com/photo-1589003077984-894e133dabab?q=80&w=800",
                            Price = 19990.0,
                            SpecificationsJson = "{\"Battery Life\":[\"20 Hours\"],\"Durability\":[\"IP67 Waterproof\"],\"Audio\":[\"360-degree sound\"]}",
                            Title = "Ultimate Ears MEGABOOM 3"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "Experience lightning-fast loading and deeper immersion.",
                            ImageUrl = "https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=800",
                            Price = 54990.0,
                            SpecificationsJson = "{\"Storage\":[\"1TB SSD\"],\"Resolution\":[\"4K at 120Hz\",\"8K Support\"],\"Drive\":[\"Disc Edition\"]}",
                            Title = "PlayStation 5 Console"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "The fastest, most powerful Xbox ever.",
                            ImageUrl = "https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=800",
                            Price = 54990.0,
                            SpecificationsJson = "{\"Storage\":[\"1TB Custom NVMe SSD\"],\"Performance\":[\"12 Teraflops\"],\"Resolution\":[\"True 4K Gaming\"]}",
                            Title = "Xbox Series X"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Play at home or on the go with a vibrant 7-inch OLED screen.",
                            ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=800",
                            Price = 34990.0,
                            SpecificationsJson = "{\"Display\":[\"7-inch OLED\"],\"Storage\":[\"64GB\"],\"Modes\":[\"TV\",\"Tabletop\",\"Handheld\"]}",
                            Title = "Nintendo Switch OLED"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "PC gaming anywhere, now with an HDR OLED display.",
                            ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=800",
                            Price = 58000.0,
                            SpecificationsJson = "{\"Display\":[\"7.4-inch HDR OLED\"],\"Storage\":[\"512GB NVMe SSD\"],\"Refresh Rate\":[\"90Hz\"]}",
                            Title = "Steam Deck OLED"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Get an edge in gameplay with customizable controls.",
                            ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=800",
                            Price = 18990.0,
                            SpecificationsJson = "{\"Platform\":[\"PS5\",\"PC\"],\"Features\":[\"Swappable Stick Modules\",\"Back Buttons\"]}",
                            Title = "DualSense Edge Wireless Controller"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "Play like a pro with adjustable-tension thumbsticks.",
                            ImageUrl = "https://images.unsplash.com/photo-1596041061998-68b759527717?q=80&w=800",
                            Price = 15990.0,
                            SpecificationsJson = "{\"Platform\":[\"Xbox\",\"PC\",\"Mobile\"],\"Battery Life\":[\"Up to 40 Hours\"],\"Features\":[\"Wrap-around rubberized grip\"]}",
                            Title = "Xbox Elite Wireless Controller Series 2"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Zero opposition. The ultimate esports gaming mouse.",
                            ImageUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800",
                            Price = 14995.0,
                            SpecificationsJson = "{\"Weight\":[\"60g\"],\"Sensor\":[\"HERO 2\",\"32K DPI\"],\"Switches\":[\"Lightforce Hybrid\"]}",
                            Title = "Logitech G Pro X Superlight 2"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "For the Pro. Ergonomic, ultra-lightweight design.",
                            ImageUrl = "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?q=80&w=800",
                            Price = 13499.0,
                            SpecificationsJson = "{\"Weight\":[\"63g\"],\"Sensor\":[\"Focus Pro 30K Optical\"],\"Polling Rate\":[\"Up to 4000Hz via Dongle\"]}",
                            Title = "Razer DeathAdder V3 Pro"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "Analog mechanical keyboard with Rapid Trigger technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=800",
                            Price = 18500.0,
                            SpecificationsJson = "{\"Switches\":[\"Lekker Magnetic Switches\"],\"Layout\":[\"60%\"],\"Features\":[\"Adjustable Actuation Point\"]}",
                            Title = "Wooting 60HE"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Magnetic-Mechanical gaming keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 19999.0,
                            SpecificationsJson = "{\"Switches\":[\"Corsair MGX Magnetic\"],\"Polling Rate\":[\"8000Hz AXON\"],\"Layout\":[\"Full Size\"]}",
                            Title = "Corsair K70 MAX RGB"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Almighty Audio experience with Active Noise Cancellation.",
                            ImageUrl = "https://images.unsplash.com/photo-1583394838336-acd977730f90?q=80&w=800",
                            Price = 32999.0,
                            SpecificationsJson = "{\"Platform\":[\"PC\",\"PS5\",\"Xbox\"],\"Features\":[\"Infinity Power System (Hot-swap Batteries)\"]}",
                            Title = "SteelSeries Arctis Nova Pro Wireless"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Studio control at your fingertips with 15 LCD keys.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Keys\":[\"15 Customizable LCD Keys\"],\"Connection\":[\"USB-C\"],\"Compatibility\":[\"Windows\",\"macOS\"]}",
                            Title = "Elgato Stream Deck MK.2"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "49-inch curved super ultrawide gaming monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1525598912003-663126343e1f?q=80&w=800",
                            Price = 165000.0,
                            SpecificationsJson = "{\"Resolution\":[\"5120 x 1440 (DQHD)\"],\"Refresh Rate\":[\"240Hz\"],\"Panel\":[\"OLED\",\"1800R Curve\"]}",
                            Title = "Samsung Odyssey OLED G9"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "34-inch QD-OLED curved gaming monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 105000.0,
                            SpecificationsJson = "{\"Resolution\":[\"3440 x 1440\"],\"Refresh Rate\":[\"165Hz\"],\"Response Time\":[\"0.1ms GtG\"]}",
                            Title = "Alienware AW3423DWF"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Description = "27-inch OLED gaming monitor with 240Hz refresh rate.",
                            ImageUrl = "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=800",
                            Price = 85000.0,
                            SpecificationsJson = "{\"Resolution\":[\"2560 x 1440 (QHD)\"],\"Refresh Rate\":[\"240Hz\"],\"Response Time\":[\"0.03ms\"]}",
                            Title = "LG UltraGear 27GR95QE"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Description = "Endgame 1440p gaming monitor with custom heatsink.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 95000.0,
                            SpecificationsJson = "{\"Resolution\":[\"2560 x 1440\"],\"Refresh Rate\":[\"240Hz\"],\"Panel\":[\"OLED\"]}",
                            Title = "ASUS ROG Swift OLED PG27AQDM"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Description = "32-inch 4K monitor with IPS Black technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=800",
                            Price = 75000.0,
                            SpecificationsJson = "{\"Resolution\":[\"3840 x 2160 (4K)\"],\"Panel\":[\"IPS Black\"],\"Color Accuracy\":[\"98% DCI-P3\"]}",
                            Title = "Dell UltraSharp U3223QE"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "A sight to be bold. 27-inch 5K Retina display.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 159900.0,
                            SpecificationsJson = "{\"Resolution\":[\"5120 x 2880 (5K)\"],\"Brightness\":[\"600 nits\"],\"Features\":[\"12MP Ultra Wide camera\"]}",
                            Title = "Apple Studio Display"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            Description = "DesignVue 32-inch 4K monitor for Mac designers.",
                            ImageUrl = "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=800",
                            Price = 89990.0,
                            SpecificationsJson = "{\"Resolution\":[\"3840 x 2160\"],\"Color Space\":[\"100% sRGB\",\"95% P3\"],\"Connectivity\":[\"Thunderbolt 3\"]}",
                            Title = "BenQ PD3220U"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            Description = "32-inch 4K gaming monitor with built-in KVM.",
                            ImageUrl = "https://images.unsplash.com/photo-1525598912003-663126343e1f?q=80&w=800",
                            Price = 65000.0,
                            SpecificationsJson = "{\"Resolution\":[\"3840 x 2160\"],\"Refresh Rate\":[\"144Hz\"],\"Features\":[\"KVM Switch\"]}",
                            Title = "Gigabyte M32U"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            Description = "Esports 4K gaming monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 48000.0,
                            SpecificationsJson = "{\"Resolution\":[\"3840 x 2160 (4K)\"],\"Refresh Rate\":[\"144Hz\"],\"Panel\":[\"Rapid IPS\"]}",
                            Title = "MSI MAG 274UPF"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            Description = "Watch, play, live in style without a PC.",
                            ImageUrl = "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=800",
                            Price = 55000.0,
                            SpecificationsJson = "{\"Resolution\":[\"4K UHD\"],\"Features\":[\"Built-in Smart TV Apps\",\"SlimFit Camera\"]}",
                            Title = "Samsung Smart Monitor M8"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            Description = "27-inch OLED 240Hz Gaming Monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 82000.0,
                            SpecificationsJson = "{\"Resolution\":[\"2560 x 1440\"],\"Refresh Rate\":[\"240Hz\"],\"Panel\":[\"OLED\"]}",
                            Title = "Acer Predator X27U"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            Description = "Porsche Design 32-inch Mini-LED Gaming Monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1525598912003-663126343e1f?q=80&w=800",
                            Price = 125000.0,
                            SpecificationsJson = "{\"Resolution\":[\"4K UHD\"],\"Panel\":[\"Mini-LED\",\"DisplayHDR 1400\"],\"Refresh Rate\":[\"144Hz\"]}",
                            Title = "AOC Agon PRO PD32M"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Description = "The ultimate sports and adventure watch.",
                            ImageUrl = "https://images.unsplash.com/photo-1544006659-f0b21f04cb1d?q=80&w=800",
                            Price = 89900.0,
                            SpecificationsJson = "{\"Material\":[\"Titanium\"],\"Display\":[\"3000 nits brightness\"],\"Battery\":[\"Up to 36 hours\"]}",
                            Title = "Apple Watch Ultra 2"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Description = "The iconic rotating bezel is back.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 36999.0,
                            SpecificationsJson = "{\"Size\":[\"43mm\",\"47mm\"],\"Material\":[\"Stainless Steel\"],\"Display\":[\"Super AMOLED\"]}",
                            Title = "Samsung Galaxy Watch 6 Classic"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Description = "Premium multisport GPS smartwatch with solar charging.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 75000.0,
                            SpecificationsJson = "{\"Features\":[\"Built-in Flashlight\",\"Solar Charging\"],\"Battery Life\":[\"Up to 22 Days\"]}",
                            Title = "Garmin Fenix 7 Pro"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            Description = "A brighter mind. Double tap gesture support.",
                            ImageUrl = "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?q=80&w=800",
                            Price = 41900.0,
                            SpecificationsJson = "{\"Size\":[\"41mm\",\"45mm\"],\"Connectivity\":[\"GPS\",\"Cellular\"],\"Processor\":[\"S9 SiP\"]}",
                            Title = "Apple Watch Series 9"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            Description = "Help by Google. Health by Fitbit.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 39999.0,
                            SpecificationsJson = "{\"Material\":[\"100% Recycled Aluminum\"],\"Sensors\":[\"Heart Rate\",\"Skin Temperature\",\"cEDA\"]}",
                            Title = "Google Pixel Watch 2"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            Description = "Revolutionary smart ring for health and sleep tracking.",
                            ImageUrl = "https://images.unsplash.com/photo-1544006659-f0b21f04cb1d?q=80&w=800",
                            Price = 28000.0,
                            SpecificationsJson = "{\"Material\":[\"Titanium\"],\"Battery Life\":[\"Up to 7 Days\"],\"Tracking\":[\"Sleep\",\"Activity\",\"Readiness\"]}",
                            Title = "Oura Ring Gen 3"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 6,
                            Description = "Advanced fitness tracker with Google apps.",
                            ImageUrl = "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Display\":[\"AMOLED Color Touchscreen\"],\"Battery Life\":[\"Up to 7 Days\"],\"Sensors\":[\"ECG\",\"GPS\"]}",
                            Title = "Fitbit Charge 6"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            Description = "24/7 fitness and health coach. Screen-free design.",
                            ImageUrl = "https://images.unsplash.com/photo-1544006659-f0b21f04cb1d?q=80&w=800",
                            Price = 25000.0,
                            SpecificationsJson = "{\"Form Factor\":[\"Wristband\",\"Apparel Integrations\"],\"Battery\":[\"Wireless Battery Pack\"]}",
                            Title = "Whoop 4.0"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            Description = "Business-styled smartwatch with dual-band GPS.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 16999.0,
                            SpecificationsJson = "{\"Display\":[\"1.43-inch AMOLED\"],\"Battery Life\":[\"Up to 14 Days\"],\"GPS\":[\"Dual-band Circularly-polarized\"]}",
                            Title = "Amazfit GTR 4"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            Description = "Ultra-thin, tough GPS multisport watch.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 45000.0,
                            SpecificationsJson = "{\"Durability\":[\"Military Grade\",\"Titanium Option\"],\"Water Resistance\":[\"100m\"],\"Battery\":[\"40h in best GPS mode\"]}",
                            Title = "Suunto 9 Peak Pro"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("DashStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
