// <auto-generated />
using System;
using DashStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406055552_changesRollBack")]
    partial class changesRollBack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2,
                            Name = "Laptops & PCs"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3,
                            Name = "Audio & Sound"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 4,
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Titanium frame and flat display.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 124999.0,
                            SpecificationsJson = "{\"Color\":[\"Titanium Black\",\"Titanium Gray\"],\"RAM\":[\"12GB\"],\"Storage\":[\"256GB\",\"512GB\"]}",
                            Title = "Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Forged in titanium.",
                            ImageUrl = "https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=800",
                            Price = 159900.0,
                            SpecificationsJson = "{\"Color\":[\"Natural Titanium\",\"Blue Titanium\"],\"RAM\":[\"8GB\"],\"Storage\":[\"256GB\",\"1TB\"]}",
                            Title = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Google AI integrated.",
                            ImageUrl = "https://images.unsplash.com/photo-1697525381593-9c869094fe26?q=80&w=800",
                            Price = 106999.0,
                            SpecificationsJson = "{\"Color\":[\"Obsidian\",\"Bay\"],\"RAM\":[\"12GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "Pixel 8 Pro"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Smooth beyond belief.",
                            ImageUrl = "https://images.unsplash.com/photo-1715437803023-74b5c77742bc?q=80&w=800",
                            Price = 64999.0,
                            SpecificationsJson = "{\"Color\":[\"Emerald\",\"Black\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB\"]}",
                            Title = "OnePlus 12"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "The ultimate foldable.",
                            ImageUrl = "https://images.unsplash.com/photo-1691435424756-32d8493f663f?q=80&w=800",
                            Price = 154999.0,
                            SpecificationsJson = "{\"Color\":[\"Phantom Black\"],\"RAM\":[\"12GB\"],\"Storage\":[\"512GB\"]}",
                            Title = "Galaxy Z Fold 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Dynamic Island standard.",
                            ImageUrl = "https://images.unsplash.com/photo-1696423602143-6c845b469493?q=80&w=800",
                            Price = 79900.0,
                            SpecificationsJson = "{\"Color\":[\"Pink\",\"Blue\"],\"RAM\":[\"6GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "iPhone 15"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Fan edition premium.",
                            ImageUrl = "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=800",
                            Price = 54999.0,
                            SpecificationsJson = "{\"Color\":[\"Mint\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "Galaxy S23 FE"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Incredible camera.",
                            ImageUrl = "https://images.unsplash.com/photo-1683935293214-3d964f40f2f3?q=80&w=800",
                            Price = 43999.0,
                            SpecificationsJson = "{\"Color\":[\"Sea\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "Pixel 7a"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Bright side of tech.",
                            ImageUrl = "https://images.unsplash.com/photo-1689254060377-5047b36f73d1?q=80&w=800",
                            Price = 44999.0,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"RAM\":[\"12GB\"],\"Storage\":[\"256GB\"]}",
                            Title = "Nothing Phone (2)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Curved display.",
                            ImageUrl = "https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=800",
                            Price = 29999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\"],\"RAM\":[\"8GB\"],\"Storage\":[\"256GB\"]}",
                            Title = "Moto Edge 40"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "A brighter mind.",
                            ImageUrl = "https://images.unsplash.com/photo-1544006659-f0b21f04cb1d?q=80&w=800",
                            Price = 41900.0,
                            SpecificationsJson = "{\"Size\":[\"45mm\"],\"Connectivity\":[\"GPS\"]}",
                            Title = "Apple Watch Series 9"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Rotating bezel.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 36999.0,
                            SpecificationsJson = "{\"Size\":[\"47mm\"],\"Color\":[\"Silver\"]}",
                            Title = "Galaxy Watch 6 Classic"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Mind-blowing performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800",
                            Price = 349900.0,
                            SpecificationsJson = "{\"Processor\":[\"M3 Max\"],\"RAM\":[\"64GB\"],\"Storage\":[\"1TB SSD\"]}",
                            Title = "MacBook Pro 16\" M3 Max"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Creator laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632559-0c6d3fc72635?q=80&w=800",
                            Price = 185000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i9\"],\"RAM\":[\"32GB\"],\"GPU\":[\"RTX 4060\"]}",
                            Title = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Gaming portability.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 145000.0,
                            SpecificationsJson = "{\"Processor\":[\"Ryzen 9\"],\"RAM\":[\"16GB\"],\"GPU\":[\"RTX 4070\"]}",
                            Title = "ASUS ROG Zephyrus G14"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Supercharged by M2.",
                            ImageUrl = "https://images.unsplash.com/photo-1611186871348-b1ec696e5237?q=80&w=800",
                            Price = 134900.0,
                            SpecificationsJson = "{\"Processor\":[\"M2\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB\"]}",
                            Title = "MacBook Air 15\" M2"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Business standard.",
                            ImageUrl = "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800",
                            Price = 165000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7\"],\"RAM\":[\"32GB\"]}",
                            Title = "Lenovo ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Premium 2-in-1.",
                            ImageUrl = "https://images.unsplash.com/photo-1544731612-de7f96afe55f?q=80&w=800",
                            Price = 139999.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7\"],\"RAM\":[\"16GB\"]}",
                            Title = "HP Spectre x360"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "High level gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1605398407421-2ba722e03282?q=80&w=800",
                            Price = 175000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7\"],\"GPU\":[\"RTX 4070\"]}",
                            Title = "Acer Predator Helios 16"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Ultra-lightweight.",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800",
                            Price = 125000.0,
                            SpecificationsJson = "{\"Weight\":[\"1.35 kg\"],\"RAM\":[\"16GB\"]}",
                            Title = "LG Gram 17"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Empower creativity.",
                            ImageUrl = "https://images.unsplash.com/photo-1629131726692-1accd0c93ce0?q=80&w=800",
                            Price = 419900.0,
                            SpecificationsJson = "{\"Processor\":[\"M2 Ultra\"],\"RAM\":[\"128GB\"]}",
                            Title = "Mac Studio M2 Ultra"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("DashStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
