// <auto-generated />
using System;
using DashStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407153439_adeedNewMonitorAndWearbles")]
    partial class adeedNewMonitorAndWearbles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2,
                            Name = "Laptops & PCs"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3,
                            Name = "Mobile Accesory  "
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3,
                            Name = "Audio & Sound  "
                        },
                        new
                        {
                            Id = 5,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 5,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 6,
                            Name = "Wearables"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 7,
                            Name = "Monitors"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 78,
                            CategoryId = 2,
                            Description = "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp\",\"https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp\",\"https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp\"]",
                            Price = 1999.99,
                            SpecificationsJson = "{\"Color\":[\"Space Grey\"],\"Processor\":[\"Apple M1 Pro\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB SSD\"],\"Display\":[\"14.2-inch Liquid Retina XDR\"]}",
                            Title = "Apple MacBook Pro 14 Inch Space Grey"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 2,
                            Description = "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp\",\"https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp\",\"https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp\"]",
                            Price = 1799.99,
                            SpecificationsJson = "{\"Color\":[\"Celestial Blue\"],\"Processor\":[\"Intel Core i9\"],\"RAM\":[\"32GB\"],\"Storage\":[\"1TB NVMe SSD\"],\"Graphics\":[\"NVIDIA GeForce RTX 3060\"]}",
                            Title = "Asus Zenbook Pro Dual Screen Laptop"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            Description = "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp\",\"https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/2.webp\",\"https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/3.webp\"]",
                            Price = 1399.99,
                            SpecificationsJson = "{\"Color\":[\"Emerald Green\"],\"Processor\":[\"Intel Core i7\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB SSD\"],\"Display\":[\"13.9-inch 3K Touchscreen\"]}",
                            Title = "Huawei Matebook X Pro"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            Description = "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp\",\"https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/2.webp\",\"https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/3.webp\"]",
                            Price = 1099.99,
                            SpecificationsJson = "{\"Color\":[\"Platinum\"],\"Processor\":[\"Intel Core i5\"],\"RAM\":[\"8GB\"],\"Storage\":[\"256GB SSD\"],\"Form Factor\":[\"2-in-1 Convertible\"]}",
                            Title = "Lenovo Yoga 920"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            Description = "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp\",\"https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/2.webp\",\"https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/3.webp\"]",
                            Price = 1499.99,
                            SpecificationsJson = "{\"Color\":[\"Silver\"],\"Processor\":[\"Intel Core i7 10th Gen\"],\"RAM\":[\"16GB\"],\"Storage\":[\"512GB SSD\"],\"Display\":[\"13.4-inch FHD\\u002B InfinityEdge\"]}",
                            Title = "New DELL XPS 13 9300 Laptop"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 1,
                            Description = "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/3.webp\"]",
                            Price = 199.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Silver\"],\"RAM\":[\"1GB\"],\"Storage\":[\"16GB\"],\"Processor\":[\"Apple A7\"],\"Screen Size\":[\"4.0 inches\"]}",
                            Title = "iPhone 5s"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 1,
                            Description = "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-6/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-6/3.webp\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Space Gray\"],\"RAM\":[\"1GB\"],\"Storage\":[\"64GB\"],\"Processor\":[\"Apple A8\"],\"Screen Size\":[\"4.7 inches\"]}",
                            Title = "iPhone 6"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 1,
                            Description = "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/3.webp\"]",
                            Price = 1099.99,
                            SpecificationsJson = "{\"Color\":[\"Sierra Blue\"],\"RAM\":[\"6GB\"],\"Storage\":[\"256GB\"],\"Processor\":[\"Apple A15 Bionic\"],\"Refresh Rate\":[\"120Hz ProMotion\"]}",
                            Title = "iPhone 13 Pro"
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 1,
                            Description = "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/iphone-x/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-x/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/iphone-x/3.webp\"]",
                            Price = 899.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Silver\"],\"RAM\":[\"3GB\"],\"Storage\":[\"64GB\"],\"Processor\":[\"Apple A11 Bionic\"],\"Display\":[\"5.8-inch Super Retina OLED\"]}",
                            Title = "iPhone X"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 1,
                            Description = "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/3.webp\"]",
                            Price = 249.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Glowing Green\"],\"RAM\":[\"4GB\"],\"Storage\":[\"64GB\"],\"Battery\":[\"5000 mAh\"],\"Camera\":[\"13MP Dual Camera\"]}",
                            Title = "Oppo A57"
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 1,
                            Description = "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/3.webp\"]",
                            Price = 399.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Space Silver\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"],\"Processor\":[\"MediaTek Dimensity 800U\"],\"Charging\":[\"50W Flash Charge\"]}",
                            Title = "Oppo F19 Pro Plus"
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 1,
                            Description = "The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/3.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/4.webp\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Astral Blue\"],\"RAM\":[\"4GB\"],\"Storage\":[\"64GB\"],\"Processor\":[\"Snapdragon 660\"],\"Security\":[\"In-Display Fingerprint\"]}",
                            Title = "Oppo K1"
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 1,
                            Description = "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/realme-c35/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-c35/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-c35/3.webp\"]",
                            Price = 149.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Glowing Black\"],\"RAM\":[\"4GB\"],\"Storage\":[\"128GB\"],\"Display\":[\"6.6-inch FHD\\u002B\"],\"Camera\":[\"50MP AI Triple Camera\"]}",
                            Title = "Realme C35"
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 1,
                            Description = "The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/realme-x/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-x/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-x/3.webp\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Polar White\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"],\"Processor\":[\"Snapdragon 710\"],\"Camera\":[\"Pop-up Selfie Camera\"]}",
                            Title = "Realme X"
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 1,
                            Description = "The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/realme-xt/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-xt/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/realme-xt/3.webp\"]",
                            Price = 349.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Pearl Blue\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"],\"Processor\":[\"Snapdragon 712\"],\"Camera\":[\"64MP Quad Camera\"]}",
                            Title = "Realme XT"
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 1,
                            Description = "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/3.webp\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Black Onyx\"],\"RAM\":[\"4GB\"],\"Storage\":[\"32GB\"],\"Display\":[\"5.1-inch Super AMOLED\"],\"Durability\":[\"IP68 Water Resistant\"]}",
                            Title = "Samsung Galaxy S7"
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 1,
                            Description = "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/3.webp\"]",
                            Price = 499.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Midnight Black\"],\"RAM\":[\"4GB\"],\"Storage\":[\"64GB\"],\"Display\":[\"5.8-inch Infinity Display\"],\"Security\":[\"Iris Scanner\"]}",
                            Title = "Samsung Galaxy S8"
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 1,
                            Description = "The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/3.webp\"]",
                            Price = 699.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Prism White\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"],\"Display\":[\"6.1-inch Dynamic AMOLED\"],\"Security\":[\"Ultrasonic Fingerprint\"]}",
                            Title = "Samsung Galaxy S10"
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 1,
                            Description = "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/3.webp\"]",
                            Price = 249.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Skyline Blue\"],\"RAM\":[\"4GB\"],\"Storage\":[\"128GB\"],\"Battery\":[\"4500 mAh\"],\"Display\":[\"Super AMOLED\"]}",
                            Title = "Vivo S1"
                        },
                        new
                        {
                            Id = 135,
                            CategoryId = 1,
                            Description = "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/3.webp\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Pearl Black\"],\"RAM\":[\"4GB\"],\"Storage\":[\"64GB\"],\"Camera\":[\"24MP AI Selfie Camera\"],\"Display\":[\"6.3-inch FHD\\u002B\"]}",
                            Title = "Vivo V9"
                        },
                        new
                        {
                            Id = 136,
                            CategoryId = 1,
                            Description = "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/1.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/2.webp\",\"https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/3.webp\"]",
                            Price = 499.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Black\"],\"RAM\":[\"6GB\"],\"Storage\":[\"128GB\"],\"Processor\":[\"Snapdragon 660\"],\"Security\":[\"In-Display Fingerprint\"]}",
                            Title = "Vivo X21"
                        },
                        new
                        {
                            Id = 159,
                            CategoryId = 2,
                            Description = "The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/1.webp\",\"https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/2.webp\",\"https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/3.webp\",\"https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/4.webp\"]",
                            Price = 499.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Starlight\"],\"Storage\":[\"64GB\"],\"Processor\":[\"A15 Bionic chip\"],\"Display\":[\"8.3-inch Liquid Retina\"],\"Connectivity\":[\"Wi-Fi\"]}",
                            Title = "iPad Mini 2021 Starlight"
                        },
                        new
                        {
                            Id = 160,
                            CategoryId = 2,
                            Description = "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/1.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/2.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/3.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/4.webp\"]",
                            Price = 599.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Graphite Grey\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"],\"Display\":[\"12.4-inch Super AMOLED\"],\"Accessories\":[\"S Pen Included\"]}",
                            Title = "Samsung Galaxy Tab S8 Plus Grey"
                        },
                        new
                        {
                            Id = 161,
                            CategoryId = 2,
                            Description = "The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/1.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/2.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/3.webp\",\"https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/4.webp\"]",
                            Price = 349.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"RAM\":[\"3GB\"],\"Storage\":[\"32GB\"],\"Display\":[\"10.1-inch TFT\"],\"Connectivity\":[\"Wi-Fi\"]}",
                            Title = "Samsung Galaxy Tab White"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 4,
                            Description = "The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/2.webp\"]",
                            Price = 99.989999999999995,
                            SpecificationsJson = "{\"Color\":[\"Charcoal\"],\"Connectivity\":[\"Wi-Fi, Bluetooth\"],\"Smart Home Hub\":[\"Built-in Zigbee\"],\"Audio\":[\"Premium Dolby Sound\"]}",
                            Title = "Amazon Echo Plus"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 4,
                            Description = "The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/2.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/3.webp\"]",
                            Price = 129.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Connectivity\":[\"Bluetooth\"],\"Battery Life\":[\"Up to 24 hours (with case)\"],\"Chip\":[\"H1 Headphone Chip\"]}",
                            Title = "Apple Airpods"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 4,
                            Description = "The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/1.webp\"]",
                            Price = 549.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Silver\"],\"Design\":[\"Over-Ear\"],\"Noise Cancellation\":[\"Active Noise Cancellation (ANC)\"],\"Battery Life\":[\"Up to 20 hours\"]}",
                            Title = "Apple AirPods Max Silver"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 3,
                            Description = "The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/1.webp\"]",
                            Price = 79.989999999999995,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Output\":[\"15W Fast Charging\"],\"Compatibility\":[\"Qi-enabled Apple Devices\"],\"Type\":[\"Wireless Charging Mat\"]}",
                            Title = "Apple Airpower Wireless Charger"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 4,
                            Description = "The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/1.webp\"]",
                            Price = 99.989999999999995,
                            SpecificationsJson = "{\"Color\":[\"Space Grey\"],\"Connectivity\":[\"Wi-Fi 802.11n\"],\"Audio\":[\"360-degree sound\"],\"Voice Assistant\":[\"Siri built-in\"]}",
                            Title = "Apple HomePod Mini Cosmic Grey"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 3,
                            Description = "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/2.webp\"]",
                            Price = 19.989999999999998,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Output\":[\"20W\"],\"Interface\":[\"USB-C\"],\"Type\":[\"Power Adapter\"]}",
                            Title = "Apple iPhone Charger"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 3,
                            Description = "The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/2.webp\"]",
                            Price = 99.989999999999995,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Capacity\":[\"1460 mAh\"],\"Compatibility\":[\"iPhone 12 and newer\"],\"Connection\":[\"Magnetic Attachment\"]}",
                            Title = "Apple MagSafe Battery Pack"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 6,
                            Description = "The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/2.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/3.webp\"]",
                            Price = 349.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Gold\"],\"Size\":[\"44mm\"],\"Connectivity\":[\"GPS \\u002B Cellular\"],\"Material\":[\"Aluminum Case\"]}",
                            Title = "Apple Watch Series 4 Gold"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 3,
                            Description = "The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/1.webp\"]",
                            Price = 49.990000000000002,
                            SpecificationsJson = "{\"Color\":[\"Beats Black\"],\"Connectivity\":[\"Bluetooth\"],\"Battery Life\":[\"Up to 12 hours\"],\"Charging\":[\"USB-C Fast Fuel\"]}",
                            Title = "Beats Flex Wireless Earphones"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 3,
                            Description = "The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/2.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/3.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/4.webp\"]",
                            Price = 29.989999999999998,
                            SpecificationsJson = "{\"Color\":[\"Plum\"],\"Material\":[\"Silicone\"],\"Compatibility\":[\"iPhone 12 / 12 Pro\"],\"Features\":[\"Built-in MagSafe\"]}",
                            Title = "iPhone 12 Silicone Case with MagSafe Plum"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 3,
                            Description = "The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/1.webp\",\"https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/2.webp\"]",
                            Price = 19.989999999999998,
                            SpecificationsJson = "{\"Color\":[\"Black\"],\"Material\":[\"Aluminum\"],\"Max Height\":[\"60 inches\"],\"Mount Type\":[\"Standard 1/4-inch screw\"]}",
                            Title = "Monopod"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 3,
                            Description = "The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/1.webp\"]",
                            Price = 14.99,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Light Levels\":[\"3 Brightness Levels\"],\"Connection\":[\"Clip-on\"],\"Power\":[\"Rechargeable USB\"]}",
                            Title = "Selfie Lamp with iPhone"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 3,
                            Description = "The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/1.webp\"]",
                            Price = 12.99,
                            SpecificationsJson = "{\"Color\":[\"Black\"],\"Connectivity\":[\"Bluetooth Remote\"],\"Folded Length\":[\"7.5 inches\"],\"Compatibility\":[\"iOS \\u0026 Android\"]}",
                            Title = "Selfie Stick Monopod"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 3,
                            Description = "The TV Studio Camera Pedestal is a professional-grade camera support system for smooth and precise camera movements in a studio setting. Ideal for broadcast and production.",
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp",
                            ImagesJson = "[\"https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/1.webp\"]",
                            Price = 499.99000000000001,
                            SpecificationsJson = "{\"Color\":[\"Black\"],\"Material\":[\"Heavy-duty Aluminum\"],\"Max Load\":[\"66 lbs (30 kg)\"],\"Mobility\":[\"Locking Casters\"]}",
                            Title = "TV Studio Camera Pedestal"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "USB 3.0 and USB 2.0 compatibility for fast data transfers and high capacity storage on the go.",
                            ImageUrl = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png\"]",
                            Price = 64.0,
                            SpecificationsJson = "{\"Capacity\":[\"2TB\"],\"Interface\":[\"USB 3.0\",\"USB 2.0\"],\"Type\":[\"HDD\"],\"Color\":[\"Black\"]}",
                            Title = "WD 2TB Elements Portable Hard Drive"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Reliable and fast internal SSD for upgrading your PC performance and boot times.",
                            ImageUrl = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png\"]",
                            Price = 109.0,
                            SpecificationsJson = "{\"Capacity\":[\"1TB\"],\"Interface\":[\"SATA III 6 Gb/s\"],\"Read Speed\":[\"535MB/s\"],\"Write Speed\":[\"450MB/s\"]}",
                            Title = "SanDisk SSD PLUS 1TB Internal SSD"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Remarkable transfer speeds that enable faster bootup and improved overall system performance.",
                            ImageUrl = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/71kWymZ\\u002Bc\\u002BL._AC_SX679_t.png\"]",
                            Price = 109.0,
                            SpecificationsJson = "{\"Capacity\":[\"256GB\"],\"Technology\":[\"3D NAND\"],\"Form Factor\":[\"2.5 inch\"],\"Interface\":[\"SATA III\"]}",
                            Title = "Silicon Power 256GB SSD 3D NAND"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "High-capacity portable storage specifically designed for a seamless PlayStation 4 gaming experience.",
                            ImageUrl = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png\"]",
                            Price = 114.0,
                            SpecificationsJson = "{\"Capacity\":[\"4TB\"],\"Compatibility\":[\"PS4\",\"PS4 Pro\"],\"Warranty\":[\"3 Years\"]}",
                            Title = "WD 4TB Gaming Drive for PS4"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "Ultra-thin widescreen IPS display with Radeon FreeSync technology for smooth visuals.",
                            ImageUrl = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png\"]",
                            Price = 599.0,
                            SpecificationsJson = "{\"Screen Size\":[\"21.5 inches\"],\"Resolution\":[\"1920 x 1080\"],\"Panel Type\":[\"IPS\"],\"Refresh Rate\":[\"75Hz\"]}",
                            Title = "Acer SB220Q 21.5-inch IPS Monitor"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "Super Ultrawide 32:9 curved gaming monitor with QLED technology and HDR support.",
                            ImageUrl = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
                            ImagesJson = "[\"https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png\"]",
                            Price = 999.99000000000001,
                            SpecificationsJson = "{\"Size\":[\"49 Inch\"],\"Refresh Rate\":[\"144Hz\"],\"Display Type\":[\"QLED\"],\"Response Time\":[\"1ms\"]}",
                            Title = "Samsung 49-Inch Curved Gaming Monitor"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            Description = "The most rugged and capable Apple Watch. Featuring a robust titanium case and dual-frequency GPS.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Fu7m3Y3iL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/71Fu7m3Y3iL._AC_SL1500_.jpg\"]",
                            Price = 799.0,
                            SpecificationsJson = "{\"Material\":[\"Titanium\"],\"Size\":[\"49mm\"],\"Battery\":[\"Up to 36 hours\"],\"Water Resistance\":[\"100m\"]}",
                            Title = "Apple Watch Ultra 2 GPS + Cellular"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "The pinnacle of Samsung wearables with advanced AI-driven health tracking and extreme durability.",
                            ImageUrl = "https://m.media-amazon.com/images/I/61N8qWInS0L._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/61N8qWInS0L._AC_SL1500_.jpg\"]",
                            Price = 649.99000000000001,
                            SpecificationsJson = "{\"OS\":[\"Wear OS 5\"],\"Processor\":[\"Exynos W1000\"],\"Display\":[\"Sapphire Crystal\"],\"Sensors\":[\"BioActive Sensor\"]}",
                            Title = "Samsung Galaxy Watch Ultra"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "Multisport GPS watch with solar charging lens and built-in LED flashlight for athletes.",
                            ImageUrl = "https://m.media-amazon.com/images/I/61mZ5Yt-TfL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/61mZ5Yt-TfL._AC_SL1500_.jpg\"]",
                            Price = 899.99000000000001,
                            SpecificationsJson = "{\"Charging\":[\"Solar Powered\"],\"Maps\":[\"Preloaded TopoActive\"],\"Flashlight\":[\"Built-in LED\"],\"Battery\":[\"Up to 37 days (Smartwatch mode)\"]}",
                            Title = "Garmin Fenix 7X Pro Solar"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Description = "The best of Google and Fitbit combined. Sleek circular design with deep integration into the Pixel ecosystem.",
                            ImageUrl = "https://m.media-amazon.com/images/I/61D5N40S-3L._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/61D5N40S-3L._AC_SL1500_.jpg\"]",
                            Price = 349.0,
                            SpecificationsJson = "{\"Display\":[\"Actua Display\"],\"Health\":[\"Daily Readiness Score\"],\"Safety\":[\"Fall Detection\"],\"Connectivity\":[\"Bluetooth/Wi-Fi\"]}",
                            Title = "Google Pixel Watch 3"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Classic look with industry-first dual-band circularly-polarized GPS antenna technology.",
                            ImageUrl = "https://m.media-amazon.com/images/I/61Yp7f1FpML._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/61Yp7f1FpML._AC_SL1500_.jpg\"]",
                            Price = 199.99000000000001,
                            SpecificationsJson = "{\"Battery\":[\"14 Days\"],\"Sports Modes\":[\"150\\u002B\"],\"Display\":[\"1.43\\u0022 AMOLED\"],\"Assistant\":[\"Alexa Built-in\"]}",
                            Title = "Amazfit GTR 4 Smart Watch"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "The world's first 32-inch 4K OLED gaming monitor with a stunning 240Hz refresh rate.",
                            ImageUrl = "https://m.media-amazon.com/images/I/81mD-mI7HlL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/81mD-mI7HlL._AC_SL1500_.jpg\"]",
                            Price = 1299.0,
                            SpecificationsJson = "{\"Resolution\":[\"3840 x 2160\"],\"Refresh Rate\":[\"240Hz\"],\"Panel\":[\"OLED\"],\"Response Time\":[\"0.03ms\"]}",
                            Title = "ASUS ROG Swift 32\" 4K OLED"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "High-performance gaming monitor with a built-in KVM switch to control multiple devices.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Y88f7R8sL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/71Y88f7R8sL._AC_SL1500_.jpg\"]",
                            Price = 299.99000000000001,
                            SpecificationsJson = "{\"Panel\":[\"IPS\"],\"Refresh Rate\":[\"170Hz\"],\"Resolution\":[\"2560 x 1440\"],\"Special Feature\":[\"KVM Switch\"]}",
                            Title = "Gigabyte M27Q 27\" QHD"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Description = "Immerse yourself in the action with a 1500R curvature and a 21:9 ultra-wide aspect ratio.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71H2l28m3BL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/71H2l28m3BL._AC_SL1500_.jpg\"]",
                            Price = 450.0,
                            SpecificationsJson = "{\"Curvature\":[\"1500R\"],\"Aspect Ratio\":[\"21:9\"],\"Resolution\":[\"UWQHD\"],\"Panel\":[\"VA\"]}",
                            Title = "MSI Optix 34\" Curved Ultrawide"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            Description = "Tailor-made for creative professionals with Mac-ready color precision and Thunderbolt 3.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71vW8o-lD0L._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/71vW8o-lD0L._AC_SL1500_.jpg\"]",
                            Price = 1099.0,
                            SpecificationsJson = "{\"Color Space\":[\"100% sRGB\",\"95% P3\"],\"Connectivity\":[\"Thunderbolt 3\",\"USB-C\"],\"Display\":[\"4K UHD IPS\"],\"Feature\":[\"Hotkey Puck G2\"]}",
                            Title = "BenQ PD3220U 32\" Designer Monitor"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            Description = "Competitive esports monitor with ultra-fast 1ms response and G-Sync compatibility.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71YyK8p6KGL._AC_SL1500_.jpg",
                            ImagesJson = "[\"https://m.media-amazon.com/images/I/71YyK8p6KGL._AC_SL1500_.jpg\"]",
                            Price = 229.0,
                            SpecificationsJson = "{\"Size\":[\"24 inch\"],\"Refresh Rate\":[\"144Hz\"],\"Sync\":[\"NVIDIA G-Sync\"],\"Resolution\":[\"1080p FHD\"]}",
                            Title = "ViewSonic ELITE 24\" 1080p"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("DashStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
