// <auto-generated />
using System;
using DashStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406092851_redo")]
    partial class redo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2,
                            Name = "Laptops & PCs"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 3,
                            Name = "Audio & Sound"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 4,
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Titanium frame and flat display.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 124999.0,
                            SpecificationsJson = "{\"Color\":[\"Titanium Black\",\"Titanium Gray\"],\"RAM\":[\"12GB\"],\"Storage\":[\"256GB\",\"512GB\"]}",
                            Title = "Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Forged in titanium.",
                            ImageUrl = "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800",
                            Price = 159900.0,
                            SpecificationsJson = "{\"Color\":[\"Natural Titanium\",\"Blue Titanium\"],\"RAM\":[\"8GB\"],\"Storage\":[\"256GB\",\"1TB\"]}",
                            Title = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Google AI integrated smartphone.",
                            ImageUrl = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800",
                            Price = 106999.0,
                            SpecificationsJson = "{\"Color\":[\"Obsidian\",\"Porcelain\",\"Bay\"],\"RAM\":[\"12GB\"],\"Storage\":[\"128GB\",\"256GB\"]}",
                            Title = "Pixel 8 Pro"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Smooth beyond belief.",
                            ImageUrl = "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=800",
                            Price = 64999.0,
                            SpecificationsJson = "{\"Color\":[\"Flowy Emerald\",\"Silky Black\"],\"RAM\":[\"12GB\",\"16GB\"],\"Storage\":[\"256GB\",\"512GB\"]}",
                            Title = "OnePlus 12"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "The ultimate foldable.",
                            ImageUrl = "https://images.unsplash.com/photo-1662955562095-8854bc8d7b38?q=80&w=800",
                            Price = 154999.0,
                            SpecificationsJson = "{\"Color\":[\"Phantom Black\",\"Icy Blue\"],\"RAM\":[\"12GB\"],\"Storage\":[\"512GB\",\"1TB\"]}",
                            Title = "Galaxy Z Fold 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Dynamic Island comes to standard models.",
                            ImageUrl = "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800",
                            Price = 79900.0,
                            SpecificationsJson = "{\"Color\":[\"Pink\",\"Yellow\",\"Green\"],\"RAM\":[\"6GB\"],\"Storage\":[\"128GB\",\"256GB\"]}",
                            Title = "iPhone 15"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Fan edition premium phone.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 54999.0,
                            SpecificationsJson = "{\"Color\":[\"Mint\",\"Graphite\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "Galaxy S23 FE"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Incredible camera, affordable price.",
                            ImageUrl = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800",
                            Price = 43999.0,
                            SpecificationsJson = "{\"Color\":[\"Charcoal\",\"Snow\",\"Sea\"],\"RAM\":[\"8GB\"],\"Storage\":[\"128GB\"]}",
                            Title = "Pixel 7a"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Come to the bright side.",
                            ImageUrl = "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=800",
                            Price = 44999.0,
                            SpecificationsJson = "{\"Color\":[\"Dark Grey\",\"White\"],\"RAM\":[\"8GB\",\"12GB\"],\"Storage\":[\"256GB\"]}",
                            Title = "Nothing Phone (2)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Ultra-slim curved display.",
                            ImageUrl = "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800",
                            Price = 29999.0,
                            SpecificationsJson = "{\"Color\":[\"Eclipse Black\",\"Nebula Green\"],\"RAM\":[\"8GB\"],\"Storage\":[\"256GB\"]}",
                            Title = "Moto Edge 40"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "A brighter mind.",
                            ImageUrl = "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?q=80&w=800",
                            Price = 41900.0,
                            SpecificationsJson = "{\"Size\":[\"41mm\",\"45mm\"],\"Connectivity\":[\"GPS\",\"Cellular\"]}",
                            Title = "Apple Watch Series 9"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "The rotating bezel is back.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800",
                            Price = 36999.0,
                            SpecificationsJson = "{\"Size\":[\"43mm\",\"47mm\"],\"Color\":[\"Black\",\"Silver\"]}",
                            Title = "Galaxy Watch 6 Classic"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Mind-blowing performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800",
                            Price = 349900.0,
                            SpecificationsJson = "{\"Processor\":[\"M3 Max\"],\"RAM\":[\"36GB\",\"64GB\"],\"Storage\":[\"1TB SSD\",\"2TB SSD\"]}",
                            Title = "MacBook Pro 16\" M3 Max"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "High performance creator laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800",
                            Price = 185000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7-13700H\",\"Intel i9-13900H\"],\"RAM\":[\"16GB\",\"32GB\"],\"GPU\":[\"RTX 4060\"]}",
                            Title = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Ultra-portable gaming laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 145000.0,
                            SpecificationsJson = "{\"Processor\":[\"Ryzen 9 7940HS\"],\"RAM\":[\"16GB\"],\"GPU\":[\"RTX 4060\",\"RTX 4070\"]}",
                            Title = "ASUS ROG Zephyrus G14"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Supercharged by M2.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800",
                            Price = 134900.0,
                            SpecificationsJson = "{\"Processor\":[\"M2\"],\"RAM\":[\"8GB\",\"16GB\"],\"Storage\":[\"256GB SSD\",\"512GB SSD\"]}",
                            Title = "MacBook Air 15\" M2"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "The ultimate business laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800",
                            Price = 165000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7-1355U\"],\"RAM\":[\"16GB\",\"32GB\"],\"Display\":[\"14 inch OLED\"]}",
                            Title = "Lenovo ThinkPad X1 Carbon"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Premium 2-in-1 convertible.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800",
                            Price = 139999.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7-1355U\"],\"RAM\":[\"16GB\"],\"Color\":[\"Nightfall Black\"]}",
                            Title = "HP Spectre x360"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Desktop-level gaming performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 175000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i7-13700HX\"],\"RAM\":[\"16GB\"],\"GPU\":[\"RTX 4070\"]}",
                            Title = "Acer Predator Helios 16"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Ultra-lightweight large screen laptop.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=800",
                            Price = 125000.0,
                            SpecificationsJson = "{\"Weight\":[\"1.35 kg\"],\"Processor\":[\"Intel i7\"],\"RAM\":[\"16GB\"]}",
                            Title = "LG Gram 17"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Empower your creativity.",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800",
                            Price = 419900.0,
                            SpecificationsJson = "{\"Processor\":[\"M2 Ultra\"],\"RAM\":[\"64GB\",\"128GB\"],\"Storage\":[\"1TB\",\"2TB\"]}",
                            Title = "Mac Studio M2 Ultra"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "High performance gaming desktop.",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800",
                            Price = 245000.0,
                            SpecificationsJson = "{\"Processor\":[\"Intel i9-13900KF\"],\"GPU\":[\"RTX 4080\",\"RTX 4090\"],\"RAM\":[\"32GB\"]}",
                            Title = "Alienware Aurora R15"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Brilliant picture, incredible design.",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800",
                            Price = 210000.0,
                            SpecificationsJson = "{\"Panel\":[\"OLED\"],\"Resolution\":[\"4K UHD\"],\"Refresh Rate\":[\"120Hz\"]}",
                            Title = "LG OLED evo C3 65\""
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Absolute detail and pure light.",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800",
                            Price = 450000.0,
                            SpecificationsJson = "{\"Panel\":[\"Mini LED\"],\"Resolution\":[\"8K UHD\"],\"Refresh Rate\":[\"144Hz\"]}",
                            Title = "Samsung Neo QLED 8K 75\""
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Master Series QD-OLED.",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800",
                            Price = 280000.0,
                            SpecificationsJson = "{\"Panel\":[\"QD-OLED\"],\"Resolution\":[\"4K\"],\"Features\":[\"Cognitive Processor XR\"]}",
                            Title = "Sony Bravia XR A95L 55\""
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Industry-leading noise cancellation.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 29990.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"Silver\",\"Midnight Blue\"],\"Battery Life\":[\"30 Hours\"],\"Features\":[\"ANC\",\"Multipoint Connection\"]}",
                            Title = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "World-class noise cancellation.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 35900.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White Smoke\"],\"Battery Life\":[\"24 Hours\"],\"Features\":[\"Immersive Audio\"]}",
                            Title = "Bose QuietComfort Ultra"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Magical audio experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=800",
                            Price = 24900.0,
                            SpecificationsJson = "{\"Color\":[\"White\"],\"Charging\":[\"USB-C\",\"MagSafe\"],\"Features\":[\"ANC\",\"Transparency\"]}",
                            Title = "AirPods Pro (2nd Gen)"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Bold sound for every adventure.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800",
                            Price = 11999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"Blue\",\"Red\"],\"Battery Life\":[\"12 Hours\"],\"Water Resistance\":[\"IP67\"]}",
                            Title = "JBL Flip 6"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Next-level spatial audio.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800",
                            Price = 44999.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White\"],\"Connectivity\":[\"Wi-Fi\",\"Bluetooth\",\"Line-in\"]}",
                            Title = "Sonos Era 300"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "Superior sound quality.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 34990.0,
                            SpecificationsJson = "{\"Battery Life\":[\"60 Hours\"],\"Color\":[\"Black\",\"White\"],\"Driver\":[\"42mm Transducer\"]}",
                            Title = "Sennheiser Momentum 4"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "Heavyweight sound in a compact frame.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Battery Life\":[\"30\\u002B Hours\"],\"Color\":[\"Black and Brass\",\"Cream\"],\"Water Resistance\":[\"IP67\"]}",
                            Title = "Marshall Emberton II"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Description = "24-bit Hi-Fi audio.",
                            ImageUrl = "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=800",
                            Price = 16999.0,
                            SpecificationsJson = "{\"Color\":[\"Graphite\",\"White\",\"Bora Purple\"],\"Features\":[\"Active Noise Canceling\"]}",
                            Title = "Samsung Galaxy Buds 2 Pro"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "Audiophile wired earbuds.",
                            ImageUrl = "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=800",
                            Price = 12990.0,
                            SpecificationsJson = "{\"Connection\":[\"3.5mm Wired\"],\"Transducer\":[\"7mm TrueResponse\"],\"Impedance\":[\"18 Ohms\"]}",
                            Title = "Sennheiser IE 200"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Description = "Professional large diaphragm headphones.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 8500.0,
                            SpecificationsJson = "{\"Design\":[\"Closed-Back\",\"Wired\"],\"Cable Type\":[\"Coiled\"],\"Driver Size\":[\"40mm\"]}",
                            Title = "Sony MDR-7506"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Zero opposition gaming mouse.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 12995.0,
                            SpecificationsJson = "{\"Color\":[\"Black\",\"White\",\"Red\"],\"Weight\":[\"\\u003C 63 grams\"],\"Sensor\":[\"HERO 25K\"]}",
                            Title = "Logitech G Pro X Superlight"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "For the Pro gamers.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 13499.0,
                            SpecificationsJson = "{\"Weight\":[\"63g\"],\"Sensor\":[\"Focus Pro 30K Optical\"],\"Polling Rate\":[\"Up to 4000 Hz\"]}",
                            Title = "Razer DeathAdder V3 Pro"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Analog mechanical keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 18500.0,
                            SpecificationsJson = "{\"Switches\":[\"Lekker Magnetic Switches\"],\"Size\":[\"60% Layout\"],\"Features\":[\"Rapid Trigger\"]}",
                            Title = "Wooting 60HE"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Legendary mechanical gaming keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Switches\":[\"Cherry MX Red\",\"Cherry MX Speed\"],\"Size\":[\"Full Size\"],\"Polling Rate\":[\"8000Hz AXON\"]}",
                            Title = "Corsair K70 RGB PRO"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Built with high performance and personalization in mind.",
                            ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=800",
                            Price = 18990.0,
                            SpecificationsJson = "{\"Compatibility\":[\"PS5\",\"PC\"],\"Features\":[\"Swappable Stick Modules\",\"Back Buttons\"]}",
                            Title = "DualSense Edge Wireless Controller"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Play like a pro.",
                            ImageUrl = "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=800",
                            Price = 15990.0,
                            SpecificationsJson = "{\"Compatibility\":[\"Xbox\",\"PC\",\"Mobile\"],\"Battery Life\":[\"Up to 40 Hours\"],\"Customization\":[\"Adjustable-tension thumbsticks\"]}",
                            Title = "Xbox Elite Wireless Controller Series 2"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "Endgame 1440p gaming monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 95000.0,
                            SpecificationsJson = "{\"Resolution\":[\"2560 x 1440\"],\"Refresh Rate\":[\"240Hz\"],\"Panel\":[\"OLED\"],\"Response Time\":[\"0.03ms\"]}",
                            Title = "ASUS ROG Swift OLED PG27AQDM"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "OLED Gaming Monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 85000.0,
                            SpecificationsJson = "{\"Resolution\":[\"2560 x 1440\"],\"Refresh Rate\":[\"240Hz\"],\"Response Time\":[\"0.03ms\"]}",
                            Title = "LG UltraGear 27GR95QE-B"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "Almighty Audio experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 32999.0,
                            SpecificationsJson = "{\"Compatibility\":[\"PC\",\"PS5\",\"Xbox\"],\"Features\":[\"Active Noise Cancellation\",\"Hot-swap Batteries\"]}",
                            Title = "SteelSeries Arctis Nova Pro Wireless"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "A legend reborn.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 14990.0,
                            SpecificationsJson = "{\"Battery Life\":[\"Up to 120 Hours\"],\"Audio\":[\"DTS Headphone:X Spatial\"],\"Microphone\":[\"Detachable with LED indicator\"]}",
                            Title = "HyperX Cloud III Wireless"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "The definitive esports gaming headset.",
                            ImageUrl = "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800",
                            Price = 16999.0,
                            SpecificationsJson = "{\"Microphone\":[\"HyperClear Super Wideband\"],\"Drivers\":[\"Triforce Titanium 50mm\"],\"Connection\":[\"2.4GHz Wireless\"]}",
                            Title = "Razer BlackShark V2 Pro"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Custom mechanical keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 18000.0,
                            SpecificationsJson = "{\"Layout\":[\"75%\"],\"Body\":[\"Full CNC Aluminum\"],\"Connectivity\":[\"Bluetooth 5.1\",\"Wired Type-C\"]}",
                            Title = "Keychron Q1 Pro"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Iconic design, reimagined.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 13995.0,
                            SpecificationsJson = "{\"Switches\":[\"Lightforce Hybrid Optical-Mechanical\"],\"RGB\":[\"8-zone array\"],\"Sensor\":[\"HERO 25K\"]}",
                            Title = "Logitech G502 X PLUS"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "49-inch curved gaming monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800",
                            Price = 135000.0,
                            SpecificationsJson = "{\"Resolution\":[\"5120 x 1440\"],\"Curve\":[\"1000R\"],\"Refresh Rate\":[\"240Hz\"]}",
                            Title = "Samsung Odyssey G9"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "Studio control at your fingertips.",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800",
                            Price = 14999.0,
                            SpecificationsJson = "{\"Keys\":[\"15 Customizable LCD Keys\"],\"Connection\":[\"USB-C\"],\"Compatibility\":[\"Windows\",\"macOS\"]}",
                            Title = "Elgato Stream Deck MK.2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("DashStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
